# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170520_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugovorstruja',
            name='omm_datum_ocitanja',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
