# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170520_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugovorstruja',
            name='mbg',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ugovorstruja',
            name='oi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ugovorstruja',
            name='oib',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ugovorstruja',
            name='omm_broj',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ugovorstruja',
            name='omm_pt_broj',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ugovorstruja',
            name='pt_broj',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
